//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventario.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar.
        /// </summary>
        internal static string BotonComprar {
            get {
                return ResourceManager.GetString("BotonComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturar.
        /// </summary>
        internal static string BotonFacturar {
            get {
                return ResourceManager.GetString("BotonFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string BotonGuardar {
            get {
                return ResourceManager.GetString("BotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al crear el producto.
        /// </summary>
        internal static string ErrorAgregarProducto {
            get {
                return ResourceManager.GetString("ErrorAgregarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad no puede ser negativa.
        /// </summary>
        internal static string ErrorCantidad {
            get {
                return ResourceManager.GetString("ErrorCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al comprar uno o más producto(s).
        /// </summary>
        internal static string ErrorComprarProducto {
            get {
                return ResourceManager.GetString("ErrorComprarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al editar el producto.
        /// </summary>
        internal static string ErrorEditarProducto {
            get {
                return ResourceManager.GetString("ErrorEditarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al facturar uno o más producto(s).
        /// </summary>
        internal static string ErrorFacturarProducto {
            get {
                return ResourceManager.GetString("ErrorFacturarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string EtiquetaActivo {
            get {
                return ResourceManager.GetString("EtiquetaActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        internal static string EtiquetaCantidad {
            get {
                return ResourceManager.GetString("EtiquetaCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string EtiquetaCodigo {
            get {
                return ResourceManager.GetString("EtiquetaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compras.
        /// </summary>
        internal static string EtiquetaCompras {
            get {
                return ResourceManager.GetString("EtiquetaCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string EtiquetaError {
            get {
                return ResourceManager.GetString("EtiquetaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string EtiquetaEstado {
            get {
                return ResourceManager.GetString("EtiquetaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas.
        /// </summary>
        internal static string EtiquetaFacturas {
            get {
                return ResourceManager.GetString("EtiquetaFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        internal static string EtiquetaInactivo {
            get {
                return ResourceManager.GetString("EtiquetaInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string EtiquetaNo {
            get {
                return ResourceManager.GetString("EtiquetaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string EtiquetaNombre {
            get {
                return ResourceManager.GetString("EtiquetaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string EtiquetaOk {
            get {
                return ResourceManager.GetString("EtiquetaOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string EtiquetaProductos {
            get {
                return ResourceManager.GetString("EtiquetaProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string EtiquetaSi {
            get {
                return ResourceManager.GetString("EtiquetaSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro del eliminar este producto.
        /// </summary>
        internal static string TextoEliminarProducto {
            get {
                return ResourceManager.GetString("TextoEliminarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventario.
        /// </summary>
        internal static string TituloApp {
            get {
                return ResourceManager.GetString("TituloApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Producto.
        /// </summary>
        internal static string TituloEliminarProducto {
            get {
                return ResourceManager.GetString("TituloEliminarProducto", resourceCulture);
            }
        }
    }
}
